# Generated by Django 4.2.2 on 2023-10-10 21:06

from django.db import migrations, models
import storage


class Migration(migrations.Migration):

    dependencies = [
        ('toothpicks', '0002_alter_contacst_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(storage=storage.OverwriteStorage(), upload_to='static/products/'),
        ),
    ]
