# Generated by Django 4.2.2 on 2023-10-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toothpicks', '0004_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacst',
            old_name='sno',
            new_name='idd',
        ),
    ]
