# Generated by Django 4.2.2 on 2023-06-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toothpicks', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.BooleanField(),
        ),
    ]
