# Generated by Django 4.2.2 on 2023-06-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toothpicks', '0009_remove_order_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
